DROP TABLE IF EXISTS book_items;
DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100),
    publisher VARCHAR(100),
    published_date DATE,
    description VARCHAR(2000),
    category VARCHAR(50) NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);




CREATE TABLE book_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    condition_type VARCHAR(20) NOT NULL,
    price NUMERIC(10, 0) NOT NULL,
    cost_price NUMERIC(10, 0),
    status VARCHAR(20) NOT NULL,
    note VARCHAR(500),
    purchased_at DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_book_items_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_category ON books(category);
CREATE INDEX idx_book_items_book_id ON book_items(book_id);
CREATE INDEX idx_book_items_status ON book_items(status);
CREATE INDEX idx_books_items_price ON book_items(price);